palabras = [
    "arroz",
    "pollo",
    "pescado",
    "ensalada",
    "pasta",
    "sopa",
    "carne",
    "verduras",
    "frutas",
    "hamburguesa",
    "pizza",
    "tacos",
    "quesadilla",
    "tortilla",
    "cebolla",
    "ajo",
    "tomate",
    "patatas",
    "queso",
    "pan",
    "jamon",
    "salchicha",
    "huevo",
    "aceitunas",
    "aceite",
    "vinagre",
    "salsa",
    "mayonesa",
    "mostaza",  
    "asado",
    "empanadas",
    "milanesa",
    "matambre a la pizza",
    "locro",
    "humita en chala",
    "choripan",
    "pastel de papas",
    "tarta de carne",
    "provoleta",
    "parrillada",
    "bife de chorizo",
    "rabas",
    "faina",
    "carbonada",
    "aguja a la criolla",
    "merluza a la napolitana",
    "tiramisu"
]


# Puedes agregar, quitar o modificar elementos según tus preferencias.
